### ISSUE TITLE
Feature: demo page (gh-pages?)

### ISSUE THREAD

**Issue by dbkaplun** [Sambego/oscilloscope.js#1]
EDIT: found [this](http://sambego.github.io/oscilloscope.js/), a bit hard to find though. Maybe link it in the description on Github? Also, a separate gh-pages branch is [no longer necessary](https://github.com/blog/2228-simpler-github-pages-publishing). Maybe put the index.html file in master to make it more obvious?

**Comment by Sambego** [comment]
Hi @dbkaplun 

The first sentence in the readme has a link to the demo page, but I added it to the description for more visibility.

Thanks for letting me know a `gh-pages` branch is no longer necessary, I'll change this soon.
